# Project information
site_name: BeeAI Workshop
site_url: https://ibm.github.io/beeai-workshop
site_author: IBM Research

# Repository
repo_name: beeai-workshop
repo_url: https://github.com/IBM/beeai-workshop
edit_uri: edit/main/docs

# Navigation
nav:
  - Welcome:
    - About BeeAI: README.md
  - Workshops:
    - Introduction to BeeAI Framework:
      - Get Started: introduction_beeai_framework/overview/README.md
    - Company Analysis Agent with the BeeAI Framework:
      - Overview: beeai_fw__tavily_redis/overview/README.md
      - Pre-Work: beeai_fw__tavily_redis/pre-work/README.md
      - Workshop Setup: beeai_fw__tavily_redis/setup/README.md
      - Create Tools: beeai_fw__tavily_redis/tools/README.md
      - Build the Agent: beeai_fw__tavily_redis/agent/README.md
      - Clean up: beeai_fw__tavily_redis/cleanup/README.md
    - Coming Soon...:
      - Building Production-Ready AI Agents in the Open Source Ecosystem:
        - Overview: opentech/overview/README.md
        - Prework: opentech/prework/README.md
        - Document Processing Labs:
          - Overview: opentech/docling/overview/README.md
          - Setup: opentech/docling/setup/README.md
        - Open Source AI Labs:
          - Overview: opentech/llm/overview/README.md
          - Setup: opentech/llm/setup/README.md
          - Lab 2: opentech/llm/lab-2/README.md
          - Lab 3: opentech/llm/lab-3/README.md
          - Lab 4: opentech/llm/lab-4/README.md
          - Lab 5: opentech/llm/lab-5/README.md
        - Agentic AI Labs:
          - BeeAI Framework: opentech/beeaiframework/README.md
          - Agent Stack: opentech/agentstack/README.md
  - Demos:
    - Introduction to BeeAI Platform:
      - Overview: introduction_beeai_platform/overview/README.md
      - Pre-work: introduction_beeai_platform/pre-work/README.md
      - Setup: introduction_beeai_platform/setup/README.md
      - Build and run the agent: introduction_beeai_platform/run/README.md
      - Uninstall & Troubleshooting: introduction_beeai_platform/uninstall_troubleshooting/README.md

  - References:
    - BeeAI Community: https://github.com/i-am-bee


## DO NOT CHANGE BELOW THIS LINE

# Copyright
copyright: Copyright &copy; 2025- BeeAI a Series of LF Projects, LLC

# Theme
theme:
  name: material
  font:
    text: IBM Plex Sans
    code: IBM Plex Mono
  icon:
    logo: material/library
  logo: images/BeeAI-Logo-White.png
  favicon: images/favicon.ico
  features:
    - navigation.tabs
    - navigation.footer
    #- navigation.instant
    - content.code.copy
  palette:
    scheme: default
    primary: black
    accent: white

# Plugins
plugins:
  - search
  - social
  - macros:
      on_undefined: strict

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/i-am-bee
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/ibmdeveloper
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/showcase/ibm-research/
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@BeeAIAgents
    - icon: fontawesome/brands/dev
      link: https://dev.to/ibmdeveloper
  colab_url: https://colab.research.google.com/github/IBM/beeai-workshop

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
